<#
.SYNOPSIS
    Scaffolds a new game by copying games/sandbox as a template, renaming
    its crate, and registering it in the workspace.

.EXAMPLE
    .\new_game.ps1 -Name mygame
#>
param(
    [Parameter(Mandatory = $true)][string]$Name
)

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$sourceDir = Join-Path $root "games\sandbox"
$destDir = Join-Path $root "games\$Name"

if (Test-Path $destDir) {
    Write-Error "games\$Name already exists"
    exit 1
}

if ($Name -notmatch '^[a-z][a-z0-9_]*$') {
    Write-Error "Name must be a valid Cargo package name: lowercase letters, digits, underscores, starting with a letter (got '$Name')"
    exit 1
}

# Directories bootstrap-generated by Sandbox::init on first run (profiles,
# levels, rigs, classes, sfx, music) or by gameplay (saves) - excluded so
# the new game gets its own fresh first-run experience via the same
# default_level()/default_demo_profiles()/etc. functions it inherits in
# src/main.rs, rather than copying the sandbox's already-played-with state.
$excludeDirs = @("profiles", "levels", "rigs", "classes", "sfx", "music", "saves")

Write-Host "Creating '$Name' from the sandbox template..." -ForegroundColor Cyan
New-Item -ItemType Directory -Path $destDir | Out-Null
Get-ChildItem $sourceDir | Where-Object { $excludeDirs -notcontains $_.Name } | ForEach-Object {
    Copy-Item $_.FullName -Destination $destDir -Recurse
}

# Rename the crate/package.
$cargoTomlPath = Join-Path $destDir "Cargo.toml"
(Get-Content $cargoTomlPath -Raw) -replace 'name = "sandbox"', "name = `"$Name`"" |
    Set-Content $cargoTomlPath -NoNewline

# Rename the window title / fatal-error dialog title in the copied source.
$mainRsPath = Join-Path $destDir "src\main.rs"
$mainRs = Get-Content $mainRsPath -Raw
$mainRs = $mainRs -replace 'Jame Engine Sandbox - Error', "Jame Engine $Name - Error"
$mainRs = $mainRs -replace 'Jame Engine Sandbox', "Jame Engine $Name"
$mainRs | Set-Content $mainRsPath -NoNewline

# Register the new crate in the workspace.
$workspaceCargoToml = Join-Path $root "Cargo.toml"
$content = Get-Content $workspaceCargoToml -Raw
$newMember = "`"games/$Name`""
if ($content -notmatch [regex]::Escape($newMember)) {
    $content = $content -replace '(members\s*=\s*\[[^\]]*)\]', "`$1, $newMember]"
    Set-Content $workspaceCargoToml $content -NoNewline
}

Write-Host "Building '$Name' to verify the scaffold..." -ForegroundColor Cyan
& cargo build -p $Name
if ($LASTEXITCODE -ne 0) {
    Write-Error "cargo build failed - check the output above"
    exit $LASTEXITCODE
}

Write-Host "Created games\$Name - run it with: cargo run -p $Name" -ForegroundColor Green
Write-Host "Demo content (Cube 1/2/3, the humanoid rig, scripts, etc.) came along for the ride - replace it with your own as you go, same as editing the sandbox directly." -ForegroundColor DarkGray
