[package]
name = "dreamscape"
version = "0.1.0"
edition = "2021"

[dependencies]
engine = { path = "../../engine" }
glam = { workspace = true }
hecs = { workspace = true }
anyhow = "1.0"
log = "0.4"
rand = "0.8"
env_logger = "0.11"
serde = { workspace = true }
ron = { workspace = true }
image = { workspace = true }

[[bin]]
name = "dreamscape"
path = "src/main.rs"
